#!/bin/bash
export ROOT="/etc/ssl/$1"
export CERTS_DIR="$ROOT/certs"
export PRIVATE_DIR="$ROOT/private"
export NEWCERTS_DIR="$ROOT/newcerts"
export CRL_DIR="$ROOT/crl"
export REQUESTS_DIR="$ROOT/requests"
export DB_DIR="$ROOT/db"
export INDEX_FILE="$DB_DIR/index.txt"
export SERIAL_FILE="$DB_DIR/serial"
export CRLNUM_FILE="$CRL_DIR/crlnumber"
CONFIG="`pwd`/openssl.cnf"
BATCH='-batch'
export KEY_C="RU"
export KEY_P="Komi Republic"
export KEY_L="Syktyvkar"
export KEY_O="$3"
export KEY_OU=""
export KEY_CN="$2"
export KEY_E="diffiehellman@mail.ru"
KEY_FILE="$PRIVATE_DIR/$KEY_CN.key"
REQ_FILE="$REQUESTS_DIR/$KEY_CN.req"
CRT_FILE="$CERTS_DIR/$KEY_CN.crt"
##====< user settings >=======
EVENT_FILE="/var/log/gs/gs.log"
export BITS="4096"
export DAYS="3650"
export ENC_KEY="no"
